apiVersion: v1
kind: Service
metadata:
  name: service-b
spec:
  type: {{ .Values.service.type }}
  selector:
    app: service-b
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
