replicaCount: 1
image:
  repository: ghcr.io/sh0jitmy/service-a
  tag: "0.1.5"
  pullPolicy: IfNotPresent
  digest: sha256:4021fb6deae269273d60b299eb2db556b22c09f8d5da2e08b7caacd6ade8ef84
service:
  type: ClusterIP
  port: 80
containerPort: 8080
resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
