replicaCount: 1
image:
  repository: ghcr.io/sh0jitmy/service-a
  tag: "0.1.5"
  pullPolicy: IfNotPresent
  digest: sha256:c4dd059dd7ef7773c99445d595762f0ee054d1adf40edc91eebcc780541eb08a
service:
  type: ClusterIP
  port: 80
containerPort: 8080
resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
