replicaCount: 1
image:
  repository: ghcr.io/yourname/service-a
  tag: "0.1.0"
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 80
containerPort: 8080
resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
